apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp-deployment
  labels:
    app: voting-app
spec:
  selector:
    matchLabels:
      name: votingapp-pod
      app: voting-app
  template:
    metadata:
      name: votingapp-pod
      labels:
        name: votingapp-pod
        app: voting-app
    spec:
      containers:
        - name: votingapp 
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 1